name: Infrastructure-Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:

  terraform:
    name: Terraform
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      working_directory: ./src/terraform/infra
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit
